# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8de24923f8afaa121a58b6159fbe8bf7e88fe0bcc927c5a197fbe595604d962f0e10385aa2b3701f5fc57243b1cd4760997bfd28c9995be050ba5a8e02c7c9

test:
  secret_key_base: 2b13366602e140defe412b118ed0644a8eed06a36ea8b9b0149a93da86aecf69878b966988a568b1db695173e2740996371843b596abd94cdab2c4a50ebd0ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
